export enum Loader {
  GET_CONNECTOR_LIST = "GET_CONNECTOR_LIST",
  GET_HTTP_TRANSACTION_LATEST_EVENTS = "GET_HTTP_TRANSACTION_LATEST_EVENTS",
  GET_HTTP_TRANSACTIONS_MONTHLY_EVENTS = "GET_HTTP_TRANSACTIONS_MONTHLY_EVENTS",
  GET_HTTP_TRANSACTIONS_MONTHLY_PER_COUNTRY_EVENTS = "GET_HTTP_TRANSACTIONS_MONTHLY_PER_COUNTRY_EVENTS",
  GET_HTTP_TRANSACTION_BYTES_SENT = "GET_HTTP_TRANSACTION_BYTES_SENT",
  GET_HTTP_TRANSACTION_RESPONSE_CODES = "GET_HTTP_TRANSACTION_RESPONSE_CODES",
  GET_ANOMALY_DETECTION_DATA = "GET_ANOMALY_DETECTION_DATA",
  GET_SECURITY_REPORT_DATA = "GET_SECURITY_REPORT_DATA",
  GET_ADVANCED_FILTERING_RESULTS = "GET_ADVANCED_FILTERING_RESULTS",
  GET_LATEST_ALERTS = "GET_LATEST_ALERTS"
}
